version: "3.4"

networks:
  example:
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16

services:
  consul:
    image: consul:1.4.2
    network_mode: host
    networks:
      example:
        ipv4_address: 172.20.0.2
    environment:
      CONSUL_ALLOW_PRIVILEGED_PORTS: ""
    command: ["-dev"]

  greeter:
    build: ./greeter-srv
    networks:
      - example
    dns: 172.20.0.1
    depends_on:
      - consul
      - vip
    command: ["-registry_address", "consul.service.consul"]

  vip:
    build: ./vip-srv
    networks:
      - example
    dns: 172.20.0.1
    depends_on:
      - consul
    command: ["-registry_address", "consul.service.consul"]

  api:
    build: ./api
    networks:
      - example
    dns: 172.20.0.1
    depends_on:
      - consul
    command: ["-registry_address", "consul.service.consul"]

  microapi:
    image: microhq/micro
    networks:
      - example
    dns: 172.20.0.1
    depends_on:
      - consul
      - api
      - greeter
      - vip
    ports:
      - "8090:8090"
    command:
      [
        "-registry_address",
        "consul.service.consul",
        "api",
        "-address",
        "0.0.0.0:8090",
      ]
